spring:
  application:
    name: eureka-server
  profiles:
    include:
      - local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:
#      default-zone: http://localhost:8761
#  server:
#    wait-time-in-ms-when-sync-empty: 5